---
# All
cert_path: "/nomad/data/certificates/ssl"

# CA Configuration
key_size: 4096
type_algorithm: "RSA"
secret_ca_passphrase: "SGFzaGljb3JwIE5vbWFkCg"
ca_file_key: "ca.key"
ca_file_certificate: "ca.pem"
common_name: "Nomad CA"

# Server Configuration
server_file_key: "server.key"
server_file_certificate: "server.pem"
server_subject_alt_name:
  domain:
    - "DNS:server.{{ region }}.nomad"
    - "DNS:*.lab.local.{{ region }}"

# Client Configuration
client_file_key: "client.key"
client_file_certificate: "client.pem"
client_subject_alt_name:
  domain:
    - "DNS:client.{{ region }}.nomad"
    - "DNS:*.lab.local.{{ region }}"